### PR TITLE
adds middleware that retrieves users role from db and updates user ob…

### PR DESCRIPTION
**Pull request by jamesjlundin**
…ject with it in index.js

## PR TITLE
**Description:** 
  
Added verifyRole function to index.js that grabs the userID from the request and retrieves that user from the database then updates the role_id of the user on the request to what is actually in the database at this point in time.
  
If an administrator was to change the role of a user that change wouldn't be reflected in the users session if the change occurred after the session was created. This middleware ensures that the request has the most up to date role data regarding the user
  
This change will verify with the database and set the role to its correct state
  
No

### CODE REVIEW

**Review by salza323 — APPROVED** [review]
Looks good. Clean and easy to read.

**Comment by s-luong07** [comment]
your code and explanation are very well lay-out and easy to understand

**Review by jakegrella — APPROVED** [review]
Sweet, thank you.

**Review by gerardo-rivera3901 — APPROVED** [review]
lgtm 👍

**Pull request merged**
